name: workflow overview

on: 
 workflow_dispatch:
 push:
   branches:
    - main
    
jobs:
 my_self_hosted_jobs:
  name: my self hosted job
  runs-on: self hosted
  steps:
   - name: step in a self hosted runner
     id: selfHostId
     shell: cmd
     run:
      echo "this is multline comment"
 a_simple_job:
  name: my sample job name
  runs-on: ubuntu-latest
  steps:
   - name: name of my step
     id: stepId
     run: echo "This is the first step from the first job"
   - name: step with another shell
     id: shellStep
     shell: python
     run: print("This step is using the python-shell")
